// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyojrzzmsnuwhahiusxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5b2pyenptc251d2hhaGl1c3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTYyNjMsImV4cCI6MjA3MTI3MjI2M30.djXTwhIHD5PYkLG4vbQTJSS84vQGkWE8kXdfC_NIfqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});